// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnFSNtLmDrQoTJMUYuInIPyHRqDsYq1ZE',
    appId: '1:502985194321:web:2014374a63a4610e8bb170',
    messagingSenderId: '502985194321',
    projectId: 'mrent-6c014',
    authDomain: 'mrent-6c014.firebaseapp.com',
    storageBucket: 'mrent-6c014.firebasestorage.app',
    measurementId: 'G-ECNDBZ2NLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHDWsB8Arts5c677z-zQWJqTNiCumVU9Q',
    appId: '1:502985194321:android:8ee7cda7ca87bbcc8bb170',
    messagingSenderId: '502985194321',
    projectId: 'mrent-6c014',
    storageBucket: 'mrent-6c014.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-znlPnvoKBxjNBnOpjlzsba7E0Ho9WN8',
    appId: '1:502985194321:ios:209f33ac1489ea278bb170',
    messagingSenderId: '502985194321',
    projectId: 'mrent-6c014',
    storageBucket: 'mrent-6c014.firebasestorage.app',
    iosBundleId: 'com.example.mrent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-znlPnvoKBxjNBnOpjlzsba7E0Ho9WN8',
    appId: '1:502985194321:ios:209f33ac1489ea278bb170',
    messagingSenderId: '502985194321',
    projectId: 'mrent-6c014',
    storageBucket: 'mrent-6c014.firebasestorage.app',
    iosBundleId: 'com.example.mrent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnFSNtLmDrQoTJMUYuInIPyHRqDsYq1ZE',
    appId: '1:502985194321:web:b8feeee8fd1f0d178bb170',
    messagingSenderId: '502985194321',
    projectId: 'mrent-6c014',
    authDomain: 'mrent-6c014.firebaseapp.com',
    storageBucket: 'mrent-6c014.firebasestorage.app',
    measurementId: 'G-Q2SFN976N2',
  );

}