// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdTLtV6Sym3qJWff5zZNGfyInB5Gur2kA',
    appId: '1:69846034338:web:8d301c5147518bf8f574fb',
    messagingSenderId: '69846034338',
    projectId: 'fir-auth-1e58f',
    authDomain: 'fir-auth-1e58f.firebaseapp.com',
    storageBucket: 'fir-auth-1e58f.firebasestorage.app',
    measurementId: 'G-WDTSC8670F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgzM14V_c3opoXJM7xi-kBk8o2Hrqpsyw',
    appId: '1:69846034338:android:f22bb3526c6c7590f574fb',
    messagingSenderId: '69846034338',
    projectId: 'fir-auth-1e58f',
    storageBucket: 'fir-auth-1e58f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC9lsHD1TPGqSV-o9XSNLnVW65xuiIOIY',
    appId: '1:69846034338:ios:37ff4656b334d987f574fb',
    messagingSenderId: '69846034338',
    projectId: 'fir-auth-1e58f',
    storageBucket: 'fir-auth-1e58f.firebasestorage.app',
    iosBundleId: 'com.example.mrent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC9lsHD1TPGqSV-o9XSNLnVW65xuiIOIY',
    appId: '1:69846034338:ios:37ff4656b334d987f574fb',
    messagingSenderId: '69846034338',
    projectId: 'fir-auth-1e58f',
    storageBucket: 'fir-auth-1e58f.firebasestorage.app',
    iosBundleId: 'com.example.mrent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdTLtV6Sym3qJWff5zZNGfyInB5Gur2kA',
    appId: '1:69846034338:web:cdcb26a926ebb23ef574fb',
    messagingSenderId: '69846034338',
    projectId: 'fir-auth-1e58f',
    authDomain: 'fir-auth-1e58f.firebaseapp.com',
    storageBucket: 'fir-auth-1e58f.firebasestorage.app',
    measurementId: 'G-BF5014MKG3',
  );
}
